<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>a199e9c3-1c90-490a-b91a-67a3c43dbf6c</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="docker包\**" />
	  <Content Remove="docker包\**" />
	  <EmbeddedResource Remove="docker包\**" />
	  <None Remove="docker包\**" />
	</ItemGroup>

<ItemGroup>
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
		<PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.2" />
		<PackageReference Include="MudBlazor" Version="8.14.0" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
		<PackageReference Include="NLog.Web.AspNetCore" Version="6.0.5" />
		<PackageReference Include="Oracle.ManagedDataAccess.Core" Version="23.9.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\DataSync.Common\DataSync.Common.csproj" />
	</ItemGroup>

</Project>







































































































































































































































































































































































