ALTER TABLE cyyy.sync_checkpoints
ADD COLUMN IF NOT EXISTS last_poll_count   INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS last_push_time    TIMESTAMP,
ADD COLUMN IF NOT EXISTS last_push_success INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS last_push_fail    INT NOT NULL DEFAULT 0;
